/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HiEveryone;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
	
	public boolean falseLibraryMethod() {
        return false;
    }
}
